sudo: required # Necessary for Travis CI
services: 
  - docker # Sets up Docker

before_install:
  - docker build -t quangche/happy-hour-app -f ./app/Dockerfile.dev ./app # Builds image 

script: 
  - docker container run quangche/happy-hour-app npm run test -- --coverage # Runs container and coverage test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "happy-hour-app"
  env: "HappyHourApp-env"
  bucket_name: "elasticbeanstalk-us-east-2-720379818253"
  bucket_path: "happy-hour-app"
  on: 
    branch: master